services:
  - type: web
    name: Library-app
    plan: free
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        value: "postgresql://library_b9x3_user:r3xPrWIXJa60FALesh7EEzP42xhwfUzb@dpg-d6t4kvlm5p6s73b5nqog-a.postgres.render.com:5432/library_b9x3"

databases:
  - name: library-db
    plan: free