default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: library_development
  username: <%= ENV['LIBRARY_DB_USER'] || 'postgres' %>

test:
  <<: *default
  database: library_test
  username: <%= ENV['LIBRARY_DB_USER'] || 'postgres' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>